GET /users/podwesley/repos HTTP/1.1
Host: api.github.com
Accept: application/json

###

GET /cozinhas
Host: localhost:8080
Accept: application/json

###

POST /cozinhas HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "cozinha": "JAPONESA"
}

###

PUT /cozinhas/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "cozinha": "JAPONESA"
}

###

DELETE /cozinhas/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
